"""
Shape-topology validation and tolerance-search utilities.

Overview
--------
This module handles the critical task of finding a convex decomposition that
matches the expected polyhedron topology. It implements a robust tolerance
iteration strategy that handles floating-point precision issues.

Tolerance Search Strategy
-------------------------
The reference workflow faces a fundamental challenge:

    Floating-point precision varies with tolerance values, causing convex
    hull algorithms to detect different numbers of edges and faces at
    different tolerances. A tolerance that's too tight might fragment faces
    into triangles; too loose might merge separate faces.

The solution is to search across a range of tolerance values from very tight
(1e-12) to loose (1e-4) and select the first one producing the expected
topology:

    Expected topology from param_file.json:
        - num_edges: 12
        - num_faces: 6

    Search process:
        Try tol=1e-12 -> gets 12 edges, 7 faces (not a match)
        Try tol=1e-11 -> gets 12 edges, 6 faces (MATCH! )
        Return this decomposition and stop searching

This robust approach works for various polyhedra despite floating-point
precision variations.

What This Module Does
---------------------
This module performs purely topological validation:

    1. Validate input vertices (shape, finite values, minimum count)
    2. Validate expected topology parameters (positive integers)
    3. Iterate through tolerance values
    4. For each tolerance, compute convex decomposition
    5. Check if decomposition matches expected topology
    6. Return first match or raise error if none found

"""

from __future__ import annotations

from typing import Iterator

import numpy as np

from .convex_decomposition import (
    ConvexDecomposition,
    convexDecomposition,
)


def decomposition_tolerances() -> Iterator[float]:
    """
    Yield tolerances in the exact order used by the reference workflow.

    This generator produces a sequence of floating-point tolerance values
    for testing convex decomposition at different precision levels.

    Tolerance Sequence
    ------------------
    The sequence ranges from very tight (small) to loose (large) precision:

        1e-12, 1e-11, 1e-10, ..., 1e-5, 1e-4

    This is generated by iterating exponents from 12 down to 4 (exclusive of 3):

        for exponent in range(12, 3, -1):
            yield 1.0 / (10 ** exponent)

    Which produces:
        1.0 / 10^12 = 1e-12
        1.0 / 10^11 = 1e-11
        ...
        1.0 / 10^4 = 1e-4

    Use in tolerance search loop:

        for tolerance in decomposition_tolerances():
            decomp = convexDecomposition(vertices, tolerance)
            if len(decomp.faces) == expected_faces:
                return decomp  # Found matching tolerance

    """

    for exponent in range(12, 3, -1):
        yield 1.0 / (10 ** exponent)


def get_shape_decomposition_matching_topology(
    vertices,
    num_faces: int,
    num_edges: int,
    verbose: bool = False,
) -> ConvexDecomposition:
    """
    Find a convex decomposition matching the expected shape topology.

    Parameters
    ----------
    vertices
        Particle vertices with shape ``(N, 3)``.

    num_faces
        Expected number of polygonal faces.

    num_edges
        Expected number of unique perimeter edges.

    verbose
        If True, print the detected topology for every tested tolerance.

    Returns
    -------
    ConvexDecomposition
        The first decomposition whose face and edge counts match the expected
        values.

    Raises
    ------
    ValueError
        If the vertices or expected topology values are invalid, or if no
        tested tolerance produces the expected topology.
    """
    vertices = np.asarray(vertices, dtype=float)

    if vertices.ndim != 2 or vertices.shape[1] != 3:
        raise ValueError(
            f"vertices must have shape (N, 3), got {vertices.shape}."
        )

    if vertices.shape[0] < 4:
        raise ValueError(
            "At least four vertices are required for a 3D convex polyhedron."
        )

    if not np.all(np.isfinite(vertices)):
        raise ValueError(
            "vertices contains NaN or infinite values."
        )

    if isinstance(num_faces, bool) or not isinstance(
        num_faces,
        (int, np.integer),
    ):
        raise ValueError(
            f"num_faces must be a positive integer, got {num_faces!r}."
        )

    if isinstance(num_edges, bool) or not isinstance(
        num_edges,
        (int, np.integer),
    ):
        raise ValueError(
            f"num_edges must be a positive integer, got {num_edges!r}."
        )

    num_faces = int(num_faces)
    num_edges = int(num_edges)

    if num_faces <= 0:
        raise ValueError(
            f"num_faces must be a positive integer, got {num_faces}."
        )

    if num_edges <= 0:
        raise ValueError(
            f"num_edges must be a positive integer, got {num_edges}."
        )

    last_decomposition = None

    for tolerance in decomposition_tolerances():
        decomposition = convexDecomposition(
            vertices,
            tolerance,
        )

        detected_faces = len(decomposition.faces)
        detected_edges = len(decomposition.edges)

        if verbose:
            print(
                f"[convexDecomposition] tol={tolerance:.1e}, "
                f"faces={detected_faces}, edges={detected_edges}"
            )

        last_decomposition = decomposition

        if (
            detected_faces == num_faces
            and detected_edges == num_edges
        ):
            if verbose:
                print(
                    "[convexDecomposition] matched JSON topology "
                    f"at tol={tolerance:.1e}"
                )

            return decomposition

    if last_decomposition is None:
        raise RuntimeError(
            "Convex-decomposition tolerance search did not execute."
        )

    raise ValueError(
        "Could not find convex decomposition matching JSON topology. "
        f"Expected faces={num_faces}, edges={num_edges}. "
        f"Last detected faces={len(last_decomposition.faces)}, "
        f"edges={len(last_decomposition.edges)}."
    )
